import { NextResponse } from 'next/server';

interface MinutesRecipient {
  name: string;
  email: string;
}

interface SendMinutesPayload {
  recipients: MinutesRecipient[];
  fileName: string;
  pdfBase64: string;
  meetingDate: string;
}

const RESEND_ENDPOINT = 'https://api.resend.com/emails';

function isOhanaEmail(email: string) {
  return /^[^\s@]+@ohanarecovery\.org$/i.test(email);
}

export async function POST(request: Request) {
  let payload: SendMinutesPayload;
  try {
    payload = (await request.json()) as SendMinutesPayload;
  } catch {
    return NextResponse.json({ error: 'Invalid request body.' }, { status: 400 });
  }

  const recipients = (payload.recipients ?? [])
    .filter((recipient) => recipient.email && isOhanaEmail(recipient.email))
    .map((recipient) => recipient.email.toLowerCase());
  const uniqueRecipients = Array.from(new Set(recipients));

  if (!uniqueRecipients.length) {
    return NextResponse.json({ error: 'No valid @ohanarecovery.org recipients were provided.' }, { status: 400 });
  }

  if (!payload.pdfBase64 || !payload.fileName) {
    return NextResponse.json({ error: 'Missing PDF attachment.' }, { status: 400 });
  }

  const apiKey = process.env.RESEND_API_KEY;

  if (!apiKey) {
    return NextResponse.json(
      { error: 'RESEND_API_KEY is not configured. Minutes were generated but not emailed.' },
      { status: 501 }
    );
  }

  const from = process.env.MINUTES_FROM_EMAIL ?? 'Ohana Recovery <minutes@ohanarecovery.org>';
  const subject = `Ohana Recovery Meeting Minutes - ${payload.meetingDate}`;
  const html = `
    <div style="font-family:Arial,sans-serif;line-height:1.6;color:#10161a">
      <p>Aloha,</p>
      <p>The official Ohana Recovery meeting minutes are attached as a password-protected PDF.</p>
      <p>Please use the minutes password shared by the secretary to open the file.</p>
      <p style="color:#52616a;font-size:13px">This record was generated by the Ohana Recovery Meeting System.</p>
    </div>
  `;

  const response = await fetch(RESEND_ENDPOINT, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      from,
      to: uniqueRecipients,
      subject,
      html,
      attachments: [
        {
          filename: payload.fileName,
          content: payload.pdfBase64,
        },
      ],
    }),
  });

  const result = await response.json().catch(() => ({}));

  if (!response.ok) {
    return NextResponse.json(
      { error: result?.message ?? result?.error ?? 'Minutes email failed to send.' },
      { status: response.status }
    );
  }

  return NextResponse.json({ sent: uniqueRecipients, providerId: result?.id });
}
